//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Model;
using System;
using System.Collections.Generic;

namespace DAL
{
	
	public partial class AdminDAL :BaseDAL<Admin>,IAdminDAL
    {
      
    }
	
	public partial class ArticleDAL :BaseDAL<Article>,IArticleDAL
    {
      
    }
	
	public partial class BlogUserDAL :BaseDAL<BlogUser>,IBlogUserDAL
    {
      
    }
	
	public partial class BuildingDAL :BaseDAL<Building>,IBuildingDAL
    {
      
    }
	
	public partial class dtpropertiesDAL :BaseDAL<dtproperties>,IdtpropertiesDAL
    {
      
    }
	
	public partial class HrefDAL :BaseDAL<Href>,IHrefDAL
    {
      
    }
	
	public partial class MessageDAL :BaseDAL<Message>,IMessageDAL
    {
      
    }
	
	public partial class ProjectDAL :BaseDAL<Project>,IProjectDAL
    {
      
    }
	
	public partial class QuantityDAL :BaseDAL<Quantity>,IQuantityDAL
    {
      
    }
	
	public partial class ReplyDAL :BaseDAL<Reply>,IReplyDAL
    {
      
    }

}