//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Model;
using System;
using System.Collections.Generic;

namespace DAL
{
	
	public partial interface IAdminDAL :IBaseDAL<Admin>
    {
      
    }
	
	public partial interface IArticleDAL :IBaseDAL<Article>
    {
      
    }
	
	public partial interface IBlogUserDAL :IBaseDAL<BlogUser>
    {
      
    }
	
	public partial interface IBuildingDAL :IBaseDAL<Building>
    {
      
    }
	
	public partial interface IdtpropertiesDAL :IBaseDAL<dtproperties>
    {
      
    }
	
	public partial interface IHrefDAL :IBaseDAL<Href>
    {
      
    }
	
	public partial interface IMessageDAL :IBaseDAL<Message>
    {
      
    }
	
	public partial interface IProjectDAL :IBaseDAL<Project>
    {
      
    }
	
	public partial interface IQuantityDAL :IBaseDAL<Quantity>
    {
      
    }
	
	public partial interface IReplyDAL :IBaseDAL<Reply>
    {
      
    }

}