//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using DAL;
using System;
using System.Collections.Generic;

namespace DALFactory
{
    //负责完成所有数据操作类DAL实例的创建
	public partial class DbSession : IDbSession
    {
	
		private IAdminDAL _AdminDAL;
        public IAdminDAL AdminDAL
        {
            get
            {
                if(_AdminDAL == null)
                {
                    _AdminDAL = AbstractDALFactory.CreateAdminDAL();
                }
                return _AdminDAL;
            }
            set { _AdminDAL = value; }
        }
	
		private IArticleDAL _ArticleDAL;
        public IArticleDAL ArticleDAL
        {
            get
            {
                if(_ArticleDAL == null)
                {
                    _ArticleDAL = AbstractDALFactory.CreateArticleDAL();
                }
                return _ArticleDAL;
            }
            set { _ArticleDAL = value; }
        }
	
		private IBlogUserDAL _BlogUserDAL;
        public IBlogUserDAL BlogUserDAL
        {
            get
            {
                if(_BlogUserDAL == null)
                {
                    _BlogUserDAL = AbstractDALFactory.CreateBlogUserDAL();
                }
                return _BlogUserDAL;
            }
            set { _BlogUserDAL = value; }
        }
	
		private IBuildingDAL _BuildingDAL;
        public IBuildingDAL BuildingDAL
        {
            get
            {
                if(_BuildingDAL == null)
                {
                    _BuildingDAL = AbstractDALFactory.CreateBuildingDAL();
                }
                return _BuildingDAL;
            }
            set { _BuildingDAL = value; }
        }
	
		private IdtpropertiesDAL _dtpropertiesDAL;
        public IdtpropertiesDAL dtpropertiesDAL
        {
            get
            {
                if(_dtpropertiesDAL == null)
                {
                    _dtpropertiesDAL = AbstractDALFactory.CreatedtpropertiesDAL();
                }
                return _dtpropertiesDAL;
            }
            set { _dtpropertiesDAL = value; }
        }
	
		private IHrefDAL _HrefDAL;
        public IHrefDAL HrefDAL
        {
            get
            {
                if(_HrefDAL == null)
                {
                    _HrefDAL = AbstractDALFactory.CreateHrefDAL();
                }
                return _HrefDAL;
            }
            set { _HrefDAL = value; }
        }
	
		private IMessageDAL _MessageDAL;
        public IMessageDAL MessageDAL
        {
            get
            {
                if(_MessageDAL == null)
                {
                    _MessageDAL = AbstractDALFactory.CreateMessageDAL();
                }
                return _MessageDAL;
            }
            set { _MessageDAL = value; }
        }
	
		private IProjectDAL _ProjectDAL;
        public IProjectDAL ProjectDAL
        {
            get
            {
                if(_ProjectDAL == null)
                {
                    _ProjectDAL = AbstractDALFactory.CreateProjectDAL();
                }
                return _ProjectDAL;
            }
            set { _ProjectDAL = value; }
        }
	
		private IQuantityDAL _QuantityDAL;
        public IQuantityDAL QuantityDAL
        {
            get
            {
                if(_QuantityDAL == null)
                {
                    _QuantityDAL = AbstractDALFactory.CreateQuantityDAL();
                }
                return _QuantityDAL;
            }
            set { _QuantityDAL = value; }
        }
	
		private IReplyDAL _ReplyDAL;
        public IReplyDAL ReplyDAL
        {
            get
            {
                if(_ReplyDAL == null)
                {
                    _ReplyDAL = AbstractDALFactory.CreateReplyDAL();
                }
                return _ReplyDAL;
            }
            set { _ReplyDAL = value; }
        }
	}	
}