//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using DAL;
using System;
using System.Collections.Generic;

namespace DALFactory
{
	public partial interface IDbSession
    {
	
		IAdminDAL AdminDAL{get;set;}
	
		IArticleDAL ArticleDAL{get;set;}
	
		IBlogUserDAL BlogUserDAL{get;set;}
	
		IBuildingDAL BuildingDAL{get;set;}
	
		IdtpropertiesDAL dtpropertiesDAL{get;set;}
	
		IHrefDAL HrefDAL{get;set;}
	
		IMessageDAL MessageDAL{get;set;}
	
		IProjectDAL ProjectDAL{get;set;}
	
		IQuantityDAL QuantityDAL{get;set;}
	
		IReplyDAL ReplyDAL{get;set;}
	}
}