//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Model;
using System;
using System.Collections.Generic;

namespace BLL
{
	
	public partial interface IAdminService : IBaseService<Admin>
    {
       
    }
	
	public partial interface IArticleService : IBaseService<Article>
    {
       
    }
	
	public partial interface IBlogUserService : IBaseService<BlogUser>
    {
       
    }
	
	public partial interface IBuildingService : IBaseService<Building>
    {
       
    }
	
	public partial interface IdtpropertiesService : IBaseService<dtproperties>
    {
       
    }
	
	public partial interface IHrefService : IBaseService<Href>
    {
       
    }
	
	public partial interface IMessageService : IBaseService<Message>
    {
       
    }
	
	public partial interface IProjectService : IBaseService<Project>
    {
       
    }
	
	public partial interface IQuantityService : IBaseService<Quantity>
    {
       
    }
	
	public partial interface IReplyService : IBaseService<Reply>
    {
       
    }
	
}